url: https://developer.nevuqe.com
title: Developer
description: "Join us, let's revolutionize the desktop."
timezone: Europe/London
exclude: ["README.md", "config.ru", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
safe: true
future: true

kramdown:
    syntax_highlighter: rouge

sass:
    style: compressed
    sass_dir: "assets/stylesheets"

defaults:
    -
        scope:
            type: "posts"
        values:
            permalink: /blog/:title/
            layout: "post"

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-menus